add dm to diff from master.

diff --git a/bin/git-misc b/bin/git-misc
--- a/bin/git-misc
+++ b/bin/git-misc
@@ -4,24 +4,22 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
-blank () {
+blank() {
   git commit --allow-empty -m "Empty commit"
   git push
 }
 
-br () {
+br() {
   git for-each-ref --sort=-committerdate refs/heads --format='%(authoremail) %(refname:short) %(committerdate:short)' | grep '^<kaix' | awk '$3 >= "'$(date -v-14d +%Y-%m-%d)'" {print $2}'
 }
 
-get-primary-branch () {
-  has_green=$(git rev-parse --verify green >/dev/null 2>&1 || echo "failed")
-  has_main=$(git rev-parse --verify main >/dev/null 2>&1 || echo "failed")
+get-primary-branch() {
+  has_green=$(git rev-parse --verify green > /dev/null 2>&1 || echo "failed")
+  has_main=$(git rev-parse --verify main > /dev/null 2>&1 || echo "failed")
 
-  if [ "x$has_green" != "xfailed" ]
-  then
+  if [ "x$has_green" != "xfailed" ]; then
     main_branch="green"
-  elif [ "x$has_main" != "xfailed" ]
-  then
+  elif [ "x$has_main" != "xfailed" ]; then
     main_branch="main"
   else
     main_branch="master"
@@ -29,21 +27,32 @@ get-primary-branch () {
   echo "$main_branch"
 }
 
-rb () {
+rb() {
   main_branch=$(get-primary-branch)
   current=$(git rev-parse --abbrev-ref HEAD)
   git co "$main_branch" && git pull && git co "${current}" && git rebase "origin/$main_branch"
 }
 
-b () {
+b() {
   main_branch=$(get-primary-branch)
   git checkout "$main_branch" && git pull && git checkout -b "$1"
 }
 
+dm() {
+  shift
+  main_branch=$(get-primary-branch)
+  if [ $# -eq 0 ]; then
+    git diff "$main_branch" --name-only
+  else
+    git diff "$main_branch" "$@"
+  fi
+}
+
 case $1 in
-    "blank") blank ;;
-    "br") br ;;
-    "rb") rb ;;
-    "b") b "$2";;
-    *) echo "Not a valid subcommand." ;;
+  "blank") blank ;;
+  "br") br ;;
+  "dm") dm "$@" ;;
+  "rb") rb ;;
+  "b") b "$2" ;;
+  *) echo "Not a valid subcommand." ;;
 esac
